version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: app
    restart: always
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    tty: true

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=nodedb
      - MYSQL_PASSWORD=nodedb
    networks: 
      - node-network

networks:
  node-network:
    driver: bridge